import { STRINGS } from './strings'

export const ACCOUNT_TYPE_SORT_ORDER = {
  [STRINGS.ACCOUNT_TYPES.SAVINGS]: 1,
  [STRINGS.ACCOUNT_TYPES.CURRENT]: 2,
  [STRINGS.ACCOUNT_TYPES.CREDIT]: 3,
  [STRINGS.ACCOUNT_TYPES.LOAN]: 4,
} as const
