import { AccountFieldConfig } from '@/lib/types/form-fields'

export const COMMON_FIELDS: AccountFieldConfig[] = [
  {
    name: 'bankName',
    label: 'Bank Name',
    type: 'text',
    placeholder: 'Enter bank name',
    required: true,
    order: 1,
    group: 'basic',
  },
  {
    name: 'accountNumber',
    label: 'Account Number',
    type: 'text',
    placeholder: 'Enter account number',
    required: true,
    order: 2,
    group: 'basic',
  },
  {
    name: 'type',
    label: 'Account Type',
    type: 'select',
    options: [
      { label: 'Savings', value: 'SAVINGS' },
      { label: 'Checking', value: 'CHECKING' },
      { label: 'Credit', value: 'CREDIT' },
      { label: 'Loan', value: 'LOAN' },
      { label: 'Salary', value: 'SALARY' },
    ],
    required: true,
    order: 3,
    group: 'basic',
  },
  {
    name: 'balance',
    label: 'Current Balance',
    type: 'number',
    step: '1000',
    placeholder: '1000',
    required: true,
    order: 4,
    group: 'financial',
  },
  {
    name: 'currency',
    label: 'Currency',
    type: 'select',
    options: [
      { label: 'INR', value: 'INR' },
      { label: 'USD', value: 'USD' },
      { label: 'EUR', value: 'EUR' },
      { label: 'GBP', value: 'GBP' },
    ],
    required: true,
    order: 5,
    group: 'financial',
  },
  {
    name: 'interestRate',
    label: 'Interest Rate (%)',
    type: 'number',
    step: '0.1',
    placeholder: '0.0',
    order: 6,
    group: 'financial',
  },
] as const
